name: Cypress Tests

on:
  workflow_dispatch:
    inputs: 
      cli:
        description: Run by cypress comand line
        default: yarn cypress run

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4.1.5
        
      - name: Instalar depenencias
        run: yarn install

      - name: Executar testes de regressão
        run: ${{ github.event.inputs.cli }}
